# This rule is not used by the project k8s-fileinfo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the info.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-fileinfo-operator
    app.kubernetes.io/managed-by: kustomize
  name: fileinfo-editor-role
rules:
- apiGroups:
  - info.example.com
  resources:
  - fileinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - info.example.com
  resources:
  - fileinfoes/status
  verbs:
  - get
